# Generated by Django 2.1.4 on 2018-12-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200, verbose_name='Имя Компании')),
                ('AddressCompany', models.CharField(max_length=200, verbose_name='Адрес Компании')),
                ('PortID', models.IntegerField(verbose_name='номер порта')),
                ('DataCreated', models.DateTimeField(verbose_name='дата время')),
                ('ProxyKey', models.CharField(max_length=50, verbose_name='ключь')),
            ],
        ),
    ]
