# Generated by Django 2.1.4 on 2018-12-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
