# Generated by Django 2.1.4 on 2018-12-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20181225_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSPORTcouter',
        ),
    ]
