# Generated by Django 2.1.4 on 2018-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_delete_rsportcouter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSPORTcouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortID', models.IntegerField(verbose_name='номер порта')),
                ('DataCreated', models.DateTimeField(verbose_name='дата время')),
                ('ProxyKey', models.CharField(max_length=50, verbose_name='ключь')),
            ],
        ),
        migrations.RemoveField(
            model_name='companies',
            name='DataCreated',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='PortID',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='ProxyKey',
        ),
    ]
